"""Shared configuration and path constants for the Spice Garden pipeline."""
import os
from pathlib import Path

from dotenv import load_dotenv

ROOT_DIR = Path(__file__).resolve().parents[2]
load_dotenv(ROOT_DIR / ".env")
SCRIPTS_DIR = ROOT_DIR / "scripts"
ASSETS_DIR = ROOT_DIR / "assets"
OUTPUT_DIR = ROOT_DIR / "output"
COST_LOG_PATH = ROOT_DIR / "cost_logs" / "usage.csv"

VIDEO_WIDTH = 1080
VIDEO_HEIGHT = 1920
VIDEO_FPS = 30
# New format (major rewrite): a clean ~50-second, no-narration, NO-ON-SCREEN-
# TEXT video built from native-audio hero clips + a couple of supporting
# stills, in the style of a continuous Studio-Ghibli cooking story with one
# consistent character. There is no voiceover and no burned-in text of any
# kind (no title, no ingredient list, no per-moment cards) - the visuals and
# the clips' own sound effects carry it, exactly like the reference the user
# provided. The ONLY on-screen text is the short animated subscribe card in
# the final seconds. Length target is ~50s: four ~10s hero clips (with their
# laggy heads trimmed) plus 1-2 stills.
TARGET_DURATION_SEC = 50
MIN_DURATION_SEC = 45
MAX_DURATION_SEC = 55
DURATION_CHECK_SLACK_SEC = 3  # review-gate tolerance around the ~50s target

BRANDING_LOGO_PATH = ASSETS_DIR / "branding" / "logo.png"
MUSIC_DIR = ASSETS_DIR / "music"

# Clip-pool: the human-in-the-loop handoff point. Hero clips are generated
# manually in Google Flow (using the Google AI Pro subscription's Flow
# credits - never via a paid API call) and dropped into CLIP_POOL_INCOMING_DIR
# as <date>-<slot>-<n>.mp4 (e.g. 2026-09-07-AM-1.mp4, 2026-09-07-AM-2.mp4 -
# n runs 1..HERO_CLIPS_PER_SHORT). Stage A watches this directory and
# requires ALL of a request's clips to be present before treating it as
# fulfilled. CLIP_POOL_PENDING_DIR holds the script.json + Flow prompt for
# each awaited request, keyed by the same <date>-<slot> pair, committed to
# the repo so a later scheduled run (possibly many hours on) can find it
# even though GitHub Actions runners don't persist state between runs.
CLIP_POOL_DIR = ROOT_DIR / "clip-pool"
CLIP_POOL_INCOMING_DIR = CLIP_POOL_DIR / "incoming"
CLIP_POOL_PENDING_DIR = CLIP_POOL_DIR / "pending"
CLIP_FILENAME_PATTERN = r"^(\d{4}-\d{2}-\d{2})-(AM|PM)-(\d+)\.mp4$"
REPORT_FILENAME = "report.json"

# Fixed, never-changing path to the most recently written brief - so
# there's exactly one file to check each day, no date/slot lookup and
# no terminal commands needed. Just open this file in a file manager.
LATEST_BRIEF_PATH = CLIP_POOL_DIR / "LATEST_BRIEF.txt"

# Review gate before publishing, per explicit user decision: run_stage_bc.py
# (what the schedule runs automatically) builds through Stage B (final.mp4)
# and stops here - it never calls Stage 7 (upload) itself. Each built,
# not-yet-approved video's final.mp4 + script.json + review_meta.json
# (bookkeeping needed to clean up clip-pool once approved) live under
# REVIEW_PENDING_DIR / <run_id> /, committed to the repo (like clip-pool)
# so they survive across ephemeral GitHub Actions runs. A human reviews
# the video, then runs scripts/approve_upload.py --run-id <id> (locally or
# via the separate approve-upload.yml manual workflow) to actually publish
# it - the only step that ever calls Stage 7.
REVIEW_PENDING_DIR = ROOT_DIR / "review-pending"

# The character reference image is NO LONGER needed by any automated
# stage: hero clips are generated manually in Flow (the human attaches
# the reference directly in Flow's own UI), and stills now come from
# Pollinations, which has no reference-image/image-to-image support.
# fetch_character_reference.py and CHARACTER_REF_URL are therefore
# optional/vestigial - kept only in case you want the pipeline to fetch
# a local copy for your own reference, not because anything requires it.
PRIVATE_ASSETS_DIR = ROOT_DIR / "_private_assets"
CHARACTER_REF_DIR = PRIVATE_ASSETS_DIR / "character_reference"
CHARACTER_REF_IMAGE_PATH = CHARACTER_REF_DIR / "reference.png"

# Confirmed Google AI Pro numbers (automation report Section 3.2) - do not
# re-derive these from pricing pages, they're account-verified. Flow charges
# per-generation credits ONLY inside the Flow web app / Gemini app UI - this
# is NOT the same billing system as the Gemini Developer API (confirmed via
# web research: "Flow credits and Gemini API billing are not interchangeable").
# Because the hero clip is now always manually generated by a human in Flow
# (see CLIP_POOL_* above), this pipeline never calls Veo via the paid API at
# all - CREDITS_PER_VEO_CLIP is used only to log an ASSUMED Flow-credit spend
# each time a manually-generated clip is consumed from the pool, for
# tracking against the 1,000/month Pro allowance. It is not a real API cost.
CREDITS_PER_VEO_CLIP = 7
MONTHLY_FLOW_CREDIT_BUDGET = 1000
# Chosen structure for the ~50-second format: 4 hero clips/video, each up to
# 10s. Clips are generated manually in the creative tool (currently Omni 1.1
# Flash at 7 credits per 360p/10s generation) and dropped into the clip pool;
# assembly upscales the 360p source to 1080x1920 and trims each clip's laggy
# head (see CLIP_LAG_TRIM_SEC). Four ~10s clips of native-audio motion, with
# their dead frames cut, plus 1-2 stills, comfortably fill ~50s. Each clip
# has its own cap (uniform 10s here, kept as a list so a future non-uniform
# structure is a one-line change); HERO_CLIPS_PER_SHORT is derived from the
# list length so the two can never drift apart - change the list, not count.
HERO_CLIP_DURATIONS_SEC = [10, 10, 10, 10]
HERO_CLIPS_PER_SHORT = len(HERO_CLIP_DURATIONS_SEC)
VEO_CLIP_DURATION_SEC = max(HERO_CLIP_DURATIONS_SEC)  # generic "up to Xs" cap, for messaging only
# CREDITS_PER_VEO_CLIP is a flat per-clip assumption (7 credits per Omni 1.1
# Flash 360p/10s generation, per the user's account). 4 clips x 7 credits x
# 2 videos/day = 56 credits/day -> 1,000/month supports ~17 sustained days.
#
# Supporting stills per video. The segment timeline is 5-6 entries total, of
# which exactly HERO_CLIPS_PER_SHORT (4) are hero clips; the remaining 1-2
# are free Pollinations stills used for slower story beats (e.g. an
# over-time step like fermenting/resting, or the finished-dish hero shot) so
# the whole ~50s isn't 4 clips held at their absolute max. These stills are
# still visuals-only - there is NO ingredient-list card or any other text.
STILLS_PER_SHORT_MIN = 1
STILLS_PER_SHORT_MAX = 2
SEGMENTS_MIN = HERO_CLIPS_PER_SHORT + STILLS_PER_SHORT_MIN  # 5
SEGMENTS_MAX = HERO_CLIPS_PER_SHORT + STILLS_PER_SHORT_MAX  # 6

VEO_MODEL_NAME = "omni-1.1-flash"  # current hero-clip model (360p/10s, 7 credits)

# Image generation: FINAL correction, after three rounds of getting this
# wrong. Gemini's image models (Nano Banana, Nano Banana 2, Imagen - all
# of them) turned out to be hard-locked to a 0 free-tier quota for any
# no-billing Google Cloud project - confirmed by testing two entirely
# separate, never-before-used projects/keys and getting the identical
# 429/limit:0 result on both. This is deliberate anti-abuse gating by
# Google (image generation is GPU-expensive), not a bug, a regional
# block, or a quota-exhaustion artifact - it applies regardless of which
# specific model ID you call. No Gemini image model is usable here
# without attaching a billing account.
#
# Switched to Pollinations.ai instead: no API key, no signup, no
# billing, genuinely free. Tradeoff: no reference-image/image-to-image
# support, so stills can't be conditioned on the character reference
# image the way a Gemini call would have been - prompts rely on text
# description alone for consistency.
IMAGE_MODEL_NAME = "pollinations-flux"
POLLINATIONS_BASE_URL = "https://image.pollinations.ai/prompt/"
POLLINATIONS_MODEL = "flux"
POLLINATIONS_REQUEST_DELAY_SEC = 2  # light courtesy delay, not a documented hard limit

# Locked-in visual style, confirmed by explicit user decision: Studio
# Ghibli-style hand-painted/watercolor anime illustration, not
# photorealism. Prepended to every still-image prompt (stage5) so it's
# guaranteed on every single generation rather than depending on Stage 1
# remembering to mention it in each beat's text. Also referenced in the
# Flow prompt instructions so hero clips match the same look.
#
# Tested empirically against real Pollinations output: appending generic
# "Studio Ghibli style, watercolor" to the END of a prompt barely changed
# the result (still came out photorealistic). Putting stronger, more
# explicit anime terms at the START of the prompt worked dramatically
# better (bold flat colors, softer illustrated edges, clearly less
# photographic) - so this is a PREFIX, not a suffix, and deliberately
# more explicit than a first attempt would guess.
VISUAL_STYLE_PREFIX = (
    "Studio Ghibli anime screenshot, Hayao Miyazaki style, 2D hand-drawn "
    "animation cel, flat cel-shaded colors, visible ink linework: "
)

GEMINI_TEXT_MODEL = os.environ.get("GEMINI_TEXT_MODEL", "gemini-3.6-flash")
# GEMINI_IMAGE_MODEL_ID and GEMINI_VIDEO_MODEL_ID have both been removed:
# this pipeline calls neither Gemini image models (see above) nor Veo via
# API (pay-as-you-go, ~$0.24-0.40/clip, separate billing from the Pro
# subscription - see stage5's docstring for the full reasoning). Hero
# clips are sourced from CLIP_POOL_INCOMING_DIR, manually generated in
# Flow; stills come from Pollinations. GEMINI_API_KEY is now only used
# by Stage 1 (script writing) and Stage 2 (review gate).


class MissingEnvVar(RuntimeError):
    pass


def require_env(name: str) -> str:
    """Fetch a required environment variable, or raise a clear, actionable error."""
    value = os.environ.get(name)
    if not value:
        raise MissingEnvVar(
            f"Required environment variable '{name}' is not set. "
            f"See SETUP.md for what each pipeline stage expects."
        )
    return value


def get_env(name: str, default=None):
    return os.environ.get(name, default)


def run_output_dir(run_id: str) -> Path:
    path = OUTPUT_DIR / run_id
    path.mkdir(parents=True, exist_ok=True)
    return path


# How long finished run folders (output/<run_id>/ - scripts, stills, audio,
# the final MP4) are kept before automatic cleanup deletes them. Requested
# by the user ("memory should clear automatically after a certain time
# period") - 14 days is a reasonable default that still leaves plenty of
# time to review a video before it's swept; override with the env var if a
# shorter/longer window is wanted. See cleanup_old_runs.py.
OUTPUT_RETENTION_DAYS = int(os.environ.get("OUTPUT_RETENTION_DAYS", "14"))


# --------------------------------------------------------------------------
# Editing / assembly look-and-feel (Stage 6). Centralised here so every
# video is cut and captioned identically - nothing about the on-screen look
# is decided per-run.
# --------------------------------------------------------------------------

# Clean, fast crossfades between every segment (clip<->still, clip<->clip).
# Short enough to keep Shorts pacing snappy, long enough to avoid a hard
# jump-cut. No flash/strobe/"disco" transitions - a plain dissolve only.
TRANSITION_DURATION_SEC = 0.25

# Per-segment hold multipliers, applied to the base beat duration so pacing
# tracks the energy of the moment: quicker cuts on prep/ingredient shots,
# a longer hold on the final plated dish. Applied in Stage 6 based on a
# segment's position/role, not baked into the script's timings.
PACING_QUICK_MULTIPLIER = 0.9   # ingredient / prep moments
PACING_HOLD_MULTIPLIER = 1.25   # final plated-dish moment

# Colour normalisation applied identically to every segment (stills AND
# clips) so the illustrated stills and the (upscaled) hero clips don't jar
# in exposure / saturation / temperature sitting next to each other. Mild on
# purpose - it unifies, it does not restyle.
COLOR_NORMALIZE_FILTER = (
    "eq=contrast=1.05:saturation=1.08:brightness=0.015:gamma=1.02"
)

# Hero clips come in at low resolution (360p on Omni 1.1 Flash) and are
# upscaled to 1080x1920, which softens them - a mild unsharp restores some
# crispness without looking processed. Applied only where it helps.
UPSCALE_SHARPEN_FILTER = "unsharp=5:5:0.6:5:5:0.0"

# Generative video clips often open with a static/warm-up "lag" frame or two
# before the real motion starts. Trim this many seconds off the HEAD of each
# hero clip when cutting its segment, so the assembled video jumps straight
# into the action (this is the "cutting the lag" the user described - it's
# also why four ~10s clips comfortably fill ~50s rather than a strict 40s).
CLIP_LAG_TRIM_SEC = 0.5

# NOTE: there is intentionally NO text-card typography here. This format
# burns in no on-screen text at all except the subscribe end-card below.

# Animated subscribe call-to-action, rendered as an overlay over the last
# SUBSCRIBE_CTA_DURATION_SEC of the video (part of the ~60s, not appended
# on top). Slides up + fades in via drawtext/overlay keyframing - no
# external animation tool. The text itself comes from the script's
# subscribe_cta_text field so it varies per video; DEFAULT is only a
# fallback when a script omits it.
SUBSCRIBE_CTA_DURATION_SEC = 3.5
SUBSCRIBE_CTA_FONT_SIZE = 88
DEFAULT_SUBSCRIBE_CTA_TEXT = "Subscribe for more"

# Google Veo stamps a "Made with Veo" / SynthID watermark fixed in the
# BOTTOM-RIGHT corner of every hero clip. It is a policy requirement that
# it stay fully visible and unobstructed, so:
#   - our channel logo goes TOP-LEFT (opposite corner), and
#   - the subscribe end-card is kept out of the bottom-right band defined
#     by these margins (there are no other on-screen overlays).
# The safe band is the bottom WATERMARK_RESERVED_H_PX pixels within the
# right WATERMARK_RESERVED_W_PX pixels - nothing we draw may enter it.
BRANDING_CORNER = "top-left"
BRANDING_MARGIN_PX = 40
BRANDING_LOGO_WIDTH_PX = 170
WATERMARK_RESERVED_W_PX = 420   # right-hand width Veo's mark can occupy
WATERMARK_RESERVED_H_PX = 240   # bottom height Veo's mark can occupy
