"""Shared configuration and path constants for the Spice Garden pipeline."""
import os
from pathlib import Path

from dotenv import load_dotenv

ROOT_DIR = Path(__file__).resolve().parents[2]
load_dotenv(ROOT_DIR / ".env")
SCRIPTS_DIR = ROOT_DIR / "scripts"
ASSETS_DIR = ROOT_DIR / "assets"
OUTPUT_DIR = ROOT_DIR / "output"
COST_LOG_PATH = ROOT_DIR / "cost_logs" / "usage.csv"

VIDEO_WIDTH = 1080
VIDEO_HEIGHT = 1920
VIDEO_FPS = 30
MIN_DURATION_SEC = 30
MAX_DURATION_SEC = 40
DURATION_CHECK_SLACK_SEC = 5  # review-gate tolerance around the 30-40s target

BRANDING_LOGO_PATH = ASSETS_DIR / "branding" / "logo.png"
MUSIC_DIR = ASSETS_DIR / "music"

# Clip-pool: the human-in-the-loop handoff point. Hero clips are generated
# manually in Google Flow (using the Google AI Pro subscription's Flow
# credits - never via a paid API call) and dropped into CLIP_POOL_INCOMING_DIR
# as <date>-<slot>-<n>.mp4 (e.g. 2026-09-07-AM-1.mp4, 2026-09-07-AM-2.mp4 -
# n runs 1..HERO_CLIPS_PER_SHORT). Stage A watches this directory and
# requires ALL of a request's clips to be present before treating it as
# fulfilled. CLIP_POOL_PENDING_DIR holds the script.json + Flow prompt for
# each awaited request, keyed by the same <date>-<slot> pair, committed to
# the repo so a later scheduled run (possibly many hours on) can find it
# even though GitHub Actions runners don't persist state between runs.
CLIP_POOL_DIR = ROOT_DIR / "clip-pool"
CLIP_POOL_INCOMING_DIR = CLIP_POOL_DIR / "incoming"
CLIP_POOL_PENDING_DIR = CLIP_POOL_DIR / "pending"
CLIP_FILENAME_PATTERN = r"^(\d{4}-\d{2}-\d{2})-(AM|PM)-(\d+)\.mp4$"
REPORT_FILENAME = "report.json"

# Fixed, never-changing path to the most recently written brief - so
# there's exactly one file to check each day, no date/slot lookup and
# no terminal commands needed. Just open this file in a file manager.
LATEST_BRIEF_PATH = CLIP_POOL_DIR / "LATEST_BRIEF.txt"

# Review gate before publishing, per explicit user decision: run_stage_bc.py
# (what the schedule runs automatically) builds through Stage B (final.mp4)
# and stops here - it never calls Stage 7 (upload) itself. Each built,
# not-yet-approved video's final.mp4 + script.json + review_meta.json
# (bookkeeping needed to clean up clip-pool once approved) live under
# REVIEW_PENDING_DIR / <run_id> /, committed to the repo (like clip-pool)
# so they survive across ephemeral GitHub Actions runs. A human reviews
# the video, then runs scripts/approve_upload.py --run-id <id> (locally or
# via the separate approve-upload.yml manual workflow) to actually publish
# it - the only step that ever calls Stage 7.
REVIEW_PENDING_DIR = ROOT_DIR / "review-pending"

# The character reference image is NO LONGER needed by any automated
# stage: hero clips are generated manually in Flow (the human attaches
# the reference directly in Flow's own UI), and stills now come from
# Pollinations, which has no reference-image/image-to-image support.
# fetch_character_reference.py and CHARACTER_REF_URL are therefore
# optional/vestigial - kept only in case you want the pipeline to fetch
# a local copy for your own reference, not because anything requires it.
PRIVATE_ASSETS_DIR = ROOT_DIR / "_private_assets"
CHARACTER_REF_DIR = PRIVATE_ASSETS_DIR / "character_reference"
CHARACTER_REF_IMAGE_PATH = CHARACTER_REF_DIR / "reference.png"

# Confirmed Google AI Pro numbers (automation report Section 3.2) - do not
# re-derive these from pricing pages, they're account-verified. Flow charges
# per-generation credits ONLY inside the Flow web app / Gemini app UI - this
# is NOT the same billing system as the Gemini Developer API (confirmed via
# web research: "Flow credits and Gemini API billing are not interchangeable").
# Because the hero clip is now always manually generated by a human in Flow
# (see CLIP_POOL_* above), this pipeline never calls Veo via the paid API at
# all - CREDITS_PER_VEO_CLIP is used only to log an ASSUMED Flow-credit spend
# each time a manually-generated clip is consumed from the pool, for
# tracking against the 1,000/month Pro allowance. It is not a real API cost.
CREDITS_PER_VEO_CLIP = 10
MONTHLY_FLOW_CREDIT_BUDGET = 1000
# Chosen structure, updated per explicit user request: 3 hero clips/video
# (up from 2), each with its OWN duration cap, in clip order - clip 1 is
# shorter (8s), clips 2-3 are longer (10s each), not a uniform cap.
# HERO_CLIPS_PER_SHORT is derived from this list's length so they can
# never drift out of sync - change the list, not the count, if this
# structure changes again.
HERO_CLIP_DURATIONS_SEC = [8, 10, 10]
HERO_CLIPS_PER_SHORT = len(HERO_CLIP_DURATIONS_SEC)
VEO_CLIP_DURATION_SEC = max(HERO_CLIP_DURATIONS_SEC)  # generic "up to Xs" cap, for messaging only
# CREDITS_PER_VEO_CLIP is still a flat per-clip assumption regardless of
# duration - unverified whether Flow actually charges more for a 10s clip
# than an 8s one; check Google AI Studio's billing dashboard for ground
# truth, same caveat as check_credit_budget.py's docstring.
# 3 clips x 10 credits x 2 videos/day = 60 credits/day -> 1,000/month
# supports ~16-17 sustained days, then a pause until the Pro renewal date
# (not yet confirmed/tracked here) - down from ~25 days under the old
# 2-clip/8s structure, since there's more real hero-clip content per video.
STILLS_PER_SHORT_MIN = 3
STILLS_PER_SHORT_MAX = 6

VEO_MODEL_NAME = "veo-3.1-lite"

# Image generation: FINAL correction, after three rounds of getting this
# wrong. Gemini's image models (Nano Banana, Nano Banana 2, Imagen - all
# of them) turned out to be hard-locked to a 0 free-tier quota for any
# no-billing Google Cloud project - confirmed by testing two entirely
# separate, never-before-used projects/keys and getting the identical
# 429/limit:0 result on both. This is deliberate anti-abuse gating by
# Google (image generation is GPU-expensive), not a bug, a regional
# block, or a quota-exhaustion artifact - it applies regardless of which
# specific model ID you call. No Gemini image model is usable here
# without attaching a billing account.
#
# Switched to Pollinations.ai instead: no API key, no signup, no
# billing, genuinely free. Tradeoff: no reference-image/image-to-image
# support, so stills can't be conditioned on the character reference
# image the way a Gemini call would have been - prompts rely on text
# description alone for consistency.
IMAGE_MODEL_NAME = "pollinations-flux"
POLLINATIONS_BASE_URL = "https://image.pollinations.ai/prompt/"
POLLINATIONS_MODEL = "flux"
POLLINATIONS_REQUEST_DELAY_SEC = 2  # light courtesy delay, not a documented hard limit

# Locked-in visual style, confirmed by explicit user decision: Studio
# Ghibli-style hand-painted/watercolor anime illustration, not
# photorealism. Prepended to every still-image prompt (stage5) so it's
# guaranteed on every single generation rather than depending on Stage 1
# remembering to mention it in each beat's text. Also referenced in the
# Flow prompt instructions so hero clips match the same look.
#
# Tested empirically against real Pollinations output: appending generic
# "Studio Ghibli style, watercolor" to the END of a prompt barely changed
# the result (still came out photorealistic). Putting stronger, more
# explicit anime terms at the START of the prompt worked dramatically
# better (bold flat colors, softer illustrated edges, clearly less
# photographic) - so this is a PREFIX, not a suffix, and deliberately
# more explicit than a first attempt would guess.
VISUAL_STYLE_PREFIX = (
    "Studio Ghibli anime screenshot, Hayao Miyazaki style, 2D hand-drawn "
    "animation cel, flat cel-shaded colors, visible ink linework: "
)

GEMINI_TEXT_MODEL = os.environ.get("GEMINI_TEXT_MODEL", "gemini-3.6-flash")
# GEMINI_IMAGE_MODEL_ID and GEMINI_VIDEO_MODEL_ID have both been removed:
# this pipeline calls neither Gemini image models (see above) nor Veo via
# API (pay-as-you-go, ~$0.24-0.40/clip, separate billing from the Pro
# subscription - see stage5's docstring for the full reasoning). Hero
# clips are sourced from CLIP_POOL_INCOMING_DIR, manually generated in
# Flow; stills come from Pollinations. GEMINI_API_KEY is now only used
# by Stage 1 (script writing) and Stage 2 (review gate).


class MissingEnvVar(RuntimeError):
    pass


def require_env(name: str) -> str:
    """Fetch a required environment variable, or raise a clear, actionable error."""
    value = os.environ.get(name)
    if not value:
        raise MissingEnvVar(
            f"Required environment variable '{name}' is not set. "
            f"See SETUP.md for what each pipeline stage expects."
        )
    return value


def get_env(name: str, default=None):
    return os.environ.get(name, default)


def run_output_dir(run_id: str) -> Path:
    path = OUTPUT_DIR / run_id
    path.mkdir(parents=True, exist_ok=True)
    return path


# How long finished run folders (output/<run_id>/ - scripts, stills, audio,
# the final MP4) are kept before automatic cleanup deletes them. Requested
# by the user ("memory should clear automatically after a certain time
# period") - 14 days is a reasonable default that still leaves plenty of
# time to review a video before it's swept; override with the env var if a
# shorter/longer window is wanted. See cleanup_old_runs.py.
OUTPUT_RETENTION_DAYS = int(os.environ.get("OUTPUT_RETENTION_DAYS", "14"))
