"""
Stage 5 - Visual generation (Pollinations.ai stills + manually-sourced hero clips).

This stage calls no Gemini API for visuals at all. Two separate models
were tried and rejected in turn:
    - Veo (video): pay-as-you-go via the Gemini Developer API
      (~$0.24-0.40 per 8s clip via generate_videos), entirely separate
      billing from the Google AI Pro subscription's Flow credits. Hero
      clips (HERO_CLIPS_PER_SHORT of them, 2 by default) are instead
      generated by a human in Flow (using already-paid-for Flow credits,
      $0 incremental cost) and handed to this stage via
      `hero_clip_paths` (see Stage A, stageA_clip_pool_watcher.py),
      mapped onto the script's "video" beats in order.
    - Stills (images): every Gemini image model (Nano Banana, Nano
      Banana 2, Imagen) turned out to be hard-locked to a 0 free-tier
      quota on any no-billing Google Cloud project - confirmed by
      testing two entirely separate, never-used projects/keys and
      getting the identical 429/limit:0 result on both. This is
      deliberate anti-abuse gating by Google, not a bug or regional
      block. Stills now come from **Pollinations.ai**
      (config.POLLINATIONS_BASE_URL) instead: no API key, no signup, no
      billing, genuinely free. Tradeoff: no reference-image/
      image-to-image support, so stills rely on text description alone
      for character consistency, not the reference image.

Visual style: config.VISUAL_STYLE_PREFIX (Studio Ghibli-style anime
illustration) is prepended to every still-image prompt here,
guaranteeing the look on every generation rather than relying on Stage 1
to mention it per-beat. It's a prefix, not a suffix - tested empirically,
front-loading the style keywords worked dramatically better against
Pollinations than appending them at the end. Hero clips get the same
style direction via the Flow prompt instructions
(generate_flow_prompt.py) instead, since that's a manual step.

Because Pollinations needs no credential at all, real stills generation
is the default - set MOCK_STILLS=1 to force flat placeholder images
instead (via Pillow), e.g. for fast/offline testing. If hero_clip_paths
is empty/not given (e.g. testing this stage standalone before real
clips exist), a placeholder solid-color video clip is used for each
"video" beat so the rest of the pipeline stays testable in isolation.

The character reference image is NOT used by this stage anymore (see
common/config.py) - it only matters for your own manual use when
generating hero clips in Flow.

Input: script.json (Stage 1 output), specifically the "visual_beats" list:
    [{"id": int, "type": "image"|"video", "prompt": str,
      "start_sec": float, "end_sec": float}, ...]
    Stage 2's review gate enforces the hybrid shape (exactly
    HERO_CLIPS_PER_SHORT video beats <=8s each, 3-6 image beats) before
    this stage ever runs.

Output (<output_dir>/):
    visuals/beat_<id>.png   (for type == "image")
    visuals/beat_<id>.mp4   (for type == "video" - copied from hero_clip_paths)
    visuals_meta.json:
        {
            "run_id": str,
            "mock_mode": bool,
            "hero_clip_sources": [str, ...],
            "beats": [{"beat_id": int, "type": str, "path": str,
                       "start_sec": float, "end_sec": float}]
        }
"""
import argparse
import logging
import shutil
import subprocess
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common.config import (
    IMAGE_MODEL_NAME, POLLINATIONS_BASE_URL, POLLINATIONS_MODEL,
    POLLINATIONS_REQUEST_DELAY_SEC, VIDEO_HEIGHT, VIDEO_WIDTH,
    VISUAL_STYLE_PREFIX, get_env, run_output_dir,
)
from common.cost_logger import log_cost
from common.io_utils import load_json, save_json
from common.retry import retry_with_backoff

logger = logging.getLogger(__name__)


@retry_with_backoff(max_attempts=3, exceptions=(RuntimeError,))
def call_image_api(prompt: str, out_path: Path):
    """Calls Pollinations.ai (free, no API key) to generate a still image
    at VIDEO_WIDTH x VIDEO_HEIGHT. Writes the result to out_path. Raises
    RuntimeError on any failure so retry_with_backoff can retry it.
    """
    encoded_prompt = urllib.parse.quote(VISUAL_STYLE_PREFIX + prompt)
    url = (
        f"{POLLINATIONS_BASE_URL}{encoded_prompt}"
        f"?width={VIDEO_WIDTH}&height={VIDEO_HEIGHT}&model={POLLINATIONS_MODEL}&nologo=true"
    )
    # Pollinations returns 403 Forbidden for Python's default urllib User-Agent
    # (bot-detection) - a browser-like one is required.
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (compatible; SpiceGardenPipeline/1.0)"})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = resp.read()
        if not data:
            raise RuntimeError("empty response body")
        out_path.write_bytes(data)
    except Exception as exc:
        raise RuntimeError(f"Pollinations still-image generation failed: {exc}") from exc


def _mock_image(prompt: str, out_path: Path):
    from PIL import Image, ImageDraw

    img = Image.new("RGB", (VIDEO_WIDTH, VIDEO_HEIGHT), color=(60, 90, 60))
    draw = ImageDraw.Draw(img)
    text = f"[MOCK IMAGE]\n{prompt[:80]}"
    draw.multiline_text((40, VIDEO_HEIGHT // 2 - 60), text, fill=(255, 255, 255))
    img.save(out_path)


def _mock_video(prompt: str, duration_sec: float, out_path: Path):
    subprocess.run(
        [
            "ffmpeg", "-y", "-f", "lavfi",
            "-i", f"color=c=0x3a5a3a:s={VIDEO_WIDTH}x{VIDEO_HEIGHT}:d={max(duration_sec, 1)}",
            "-vf", f"drawtext=text='[MOCK VIDEO] {prompt[:40]}':fontcolor=white:fontsize=36:"
                   "x=(w-text_w)/2:y=(h-text_h)/2",
            "-c:v", "libx264", "-t", str(max(duration_sec, 1)), str(out_path),
        ],
        check=True, capture_output=True,
    )


def generate_visuals(script_path: str, output_dir: str, run_id: str, hero_clip_paths: list = None) -> dict:
    script = load_json(script_path)
    beats = script.get("visual_beats", [])
    hero_clip_paths = list(hero_clip_paths) if hero_clip_paths else []
    hero_clip_iter = iter(hero_clip_paths)

    out_dir = Path(output_dir)
    visuals_dir = out_dir / "visuals"
    visuals_dir.mkdir(parents=True, exist_ok=True)

    mock_mode = get_env("MOCK_STILLS", "").lower() in ("1", "true", "yes")
    if mock_mode:
        logger.warning("MOCK_STILLS set - generating mock placeholder stills instead of calling Pollinations.")

    result_beats = []
    real_image_calls_made = 0
    for beat in beats:
        beat_id = beat["id"]
        beat_type = beat["type"]
        duration = beat["end_sec"] - beat["start_sec"]

        if beat_type == "image":
            out_path = visuals_dir / f"beat_{beat_id}.png"
            if mock_mode:
                _mock_image(beat["prompt"], out_path)
            else:
                if real_image_calls_made > 0:
                    time.sleep(POLLINATIONS_REQUEST_DELAY_SEC)
                call_image_api(beat["prompt"], out_path)
                real_image_calls_made += 1
                log_cost(
                    run_id=run_id, stage="stage5_visual_generation",
                    provider="pollinations", model=POLLINATIONS_MODEL, units=1,
                    unit_type="image_generation", cost_usd=0.0,
                    notes="still - free, no API key",
                )
        elif beat_type == "video":
            out_path = visuals_dir / f"beat_{beat_id}.mp4"
            hero_clip_path = next(hero_clip_iter, None)
            if hero_clip_path:
                shutil.copy(hero_clip_path, out_path)
                logger.info("Hero clip copied from clip-pool: %s", hero_clip_path)
            else:
                logger.warning("No hero clip available for beat %d - using a mock placeholder video beat.", beat_id)
                _mock_video(beat["prompt"], duration, out_path)
        else:
            raise ValueError(f"Unknown visual beat type: {beat_type!r}")

        result_beats.append({
            "beat_id": beat_id,
            "type": beat_type,
            "path": str(out_path.relative_to(out_dir)),
            "start_sec": beat["start_sec"],
            "end_sec": beat["end_sec"],
        })

    meta = {
        "run_id": run_id,
        "mock_mode": mock_mode,
        "hero_clip_sources": [str(p) for p in hero_clip_paths],
        "beats": result_beats,
    }
    save_json(out_dir / "visuals_meta.json", meta)

    image_beat_count = sum(1 for b in beats if b.get("type") == "image")
    log_cost(
        run_id=run_id, stage="stage5_visual_generation",
        provider="mock" if mock_mode else "pollinations",
        model="mock" if mock_mode else IMAGE_MODEL_NAME,
        units=image_beat_count, unit_type="assets",
        cost_usd=0.0, notes="mock mode" if mock_mode else "stills summary - see per-asset rows above",
    )
    logger.info("Generated %d visual assets (mock_mode=%s)", len(result_beats), mock_mode)
    return meta


def main():
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description="Stage 5: visual generation")
    parser.add_argument("--script", required=True, help="Path to script.json")
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--output-dir", default=None)
    parser.add_argument(
        "--hero-clip", dest="hero_clips", action="append", default=None,
        help="Path to a manually-generated hero clip from the clip pool (repeat for multiple)",
    )
    args = parser.parse_args()

    output_dir = args.output_dir or str(run_output_dir(args.run_id))
    generate_visuals(args.script, output_dir, args.run_id, args.hero_clips)


if __name__ == "__main__":
    main()
